### ISSUE TITLE
프레임을 각각 입력해야한다는 안내 문구를 추가

### ISSUE THREAD

**Issue by baesy0** [75mm-studio/estimate#166]

**Comment by baesy0** [comment]
예제도 기입

**Comment by baesy0** [comment]
컷 별 프레임 수를 각각 입력해주세요.
ex) 260 + 35 + 115

**Comment by khw7096** [comment]
history가 10줄로 늘어난다. 최초 안내문이 작성되어있고, 계산기를 작동하면 안내문이 사라지고 history가 입력된다.

**Comment by baesy0** [comment]
https://stackoverflow.com/questions/26960417/when-a-span-element-contains-no-text-fill-with-placeholder-text

**Comment by baesy0** [comment]
https://developer.mozilla.org/ko/docs/Web/CSS/::before

**Comment by baesy0** [comment]
content 내부에서 줄바꿈 하는 법
https://developer.mozilla.org/ko/docs/Web/CSS/white-space
