### ISSUE TITLE
calHistory가 단어기준으로 줄바꿈 되도록 하기

### ISSUE THREAD

**Issue by baesy0** [75mm-studio/estimate#168]

**Comment by khw7096** [comment]
뒤에도 붙혀야한다.

**Comment by baesy0** [comment]
추가해봤는데 숫자가 중간에 줄바꿈되는 문제가 해결되는거 같지 않아요.
좀 더 논의해봐야 할 거 같아요!

**Comment by baesy0** [comment]
<img width="238" alt="image" src="https://user-images.githubusercontent.com/40417084/76601809-0ccefb80-654d-11ea-808f-f39af38c3dd9.png">

**Comment by khw7096** [comment]
아직 css 항목이 추가되지 않아서 그래요.

**Comment by khw7096** [comment]
이건 같이 고민해봐요.
