### ISSUE TITLE
onset map

### ISSUE THREAD

**Issue by baesy0** [75mm-studio/estimate#198]
- 서버 구축
- 느리지 않았으면 좋겠다.
- 아마존: 상한 10만원
- S3 vs EC2 vs 나스설치
    - S3: 100T이상일 경우 100명 당 약 2만 6천 /. 100만명 당 약 2억 6천
    - EC2: 메모리 8G이상일 경우 1년에 약 100만원 예상
    - 나스:

**Comment by khw7096** [comment]
이 이슈는 web 리포지터리로 옮길께요.!
