### ISSUE TITLE
meta: 한 컷에 여러 오브젝트를 잡을 때, 

### ISSUE THREAD

**Issue by baesy0** [75mm-studio/estimate#92]
클라이언트 측에서 비싸다는 의견이 있음.
여러 오브젝트가 한 컷에 들어갈 경우 할인률 적용할지 논의 중

**Comment by khw7096** [comment]
한컷에 너무 많은 오브젝트 트렉킹이 있을 때 조율 하는 문구를 넣기.

**Comment by khw7096** [comment]
프레임 계산기 방식으로 수정방향을 잡음.
